# Generated by Django 5.0 on 2024-07-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('new_price', models.CharField(default=' ', max_length=10)),
                ('old_price', models.CharField(default=' ', max_length=10)),
            ],
        ),
    ]
