# Generated by Django 5.0.8 on 2024-08-16 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_citems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citems',
            old_name='cartid',
            new_name='cart_id',
        ),
        migrations.RenameField(
            model_name='citems',
            old_name='productid',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='citems',
            old_name='userid',
            new_name='user_id',
        ),
    ]
