# Generated by Django 5.0 on 2024-08-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_cartid_citems_cart_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citems',
            name='cart_id',
        ),
    ]
