# Generated by Django 5.0.8 on 2024-08-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_citems_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='citems',
            name='cart_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
